spring:
  application:
    name: libraryapi
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
#      ddl-auto: update // Faz com que as tabelas sejam criadas dinamicamente
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true]
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 190290003630-g5is505ggal54c1mus7g7rlc56s29146.apps.googleusercontent.com
            client-secret: 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
server:
  port: 8081